version: "3.7"

services:
  xm-db:
    container_name: xm-db
    image: postgres:14.1
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - "15432:5432"
    restart: on-failure
    networks:
      - xm-db

networks:
  xm-db: